[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/api/ping"
  to = "https://hirez-backend.netlify.app/.netlify/functions/api/ping"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "/api/createsession"
  to = "https://hirez-backend.netlify.app/.netlify/functions/api/createsession"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

    [[redirects]]
  from = "/api/getchampions"
  to = "https://hirez-backend.netlify.app/.netlify/functions/api/getchampions"
  status = 200
  force = true
  headers = {X-From = "Netlify"}