[[redirects]]
  from = "/api/*"
  to = "https://api.paladins.com/paladinsapi.svc/:splat"
  status = 200

  [[redirects]]
  from = "/*"
  to = "/"
  status = 200

  [[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

    [[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200